name: the c1 project
description: This is a short description.
author:
  name: Chris Tate
  email: test@crystal.sh
  url: 'http://crystalcodegen.com'
copyright: 2015 Chris Tate
imports:
  crystal/angular: ~0.3.0
  crystal/bower: ~0.4.1
  crystal/npm: ~0.3.1
