name: the c1 project
description: 'This is a short description!'
author:
  name: Test User
  email: test@example.com
  url: 'http://example.com'
copyright: 2015 Example
imports:
  crystal/angular: ~0.3.0
  crystal/bower: ~0.4.1
  crystal/npm: ~0.3.1
